# analyzer:
#   errors:
#     unused_local_variable: ignore
#     unused_field: ignore
#     unused_element: ignore
#     unused_import: ignore
#     unused_label: ignore
#     unused_shown_name: ignore

# linter:
#   rules:
#     unused_local_variable: ignore
#     unused_field: ignore
#     unused_element: ignore
#     unused_import: ignore
#     unused_label: ignore
#     unused_shown_name: ignore
